name: Release CLI

on:
  push:
    tags:
      - releases/cli/*
jobs:
  create_cli_release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna run test
        env:
          CI: true
      - run: npx lerna run build
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'packages/cli/dist/**/*.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
