name: Release Beta File Storage

on:
  push:
    tags:
      - 'releases/file-storage/**-beta*'

jobs:
  create_file_storage_release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
        env:
          CI: true
      # It is currently a dependency
      - run: npx lerna run build --scope '@meeco/sdk'
      # Tag all versions with `-beta` and update all inter-dependant packages to use "beta" as the version
      - run: npm run beta
      - run: npx lerna run build --scope '@meeco/{file-storage-common,file-storage-browser,file-storage-node}'
      - name: Publish NPM
        run: |
          npx lerna exec --scope '@meeco/{file-storage-common,file-storage-browser,file-storage-node}' -- npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npx lerna exec --scope '@meeco/{file-storage-common,file-storage-browser,file-storage-node}' -- npm config set scope "@meeco"
          npx lerna exec --scope '@meeco/{file-storage-common,file-storage-browser,file-storage-node}' -- npm publish --access public --tag beta
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
