name: Release Beta SDK

on:
  push:
    tags:
      - 'releases/sdk/**-beta'

jobs:
  create_sdk_beta_release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna run test
        env:
          CI: true
      - run: npx lerna run build --scope @meeco/sdk
      - name: Publish NPM
        run: |
          npx lerna exec --scope @meeco/sdk -- npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npx lerna exec --scope @meeco/sdk -- npm config set scope "@meeco"
          npx lerna exec --scope @meeco/sdk -- npm publish --access public --tag beta
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
      - name: Build SDK Demo
        run:  npx lerna run build --scope @meeco/sdk-demo
      - name: Deploy SDK Demo GH page
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SDK_DOCS_DEPLOY_KEY }}
          publish_dir: ./docs/sdk-demo
          destination_dir: /stage/sdk-demo
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          external_repository: Meeco/sdk-docs
          publish_branch: master
